os:
- linux
- osx
- windows

dist: bionic

language: node_js
node_js:
  - lts/dubnium
  - lts/erbium
  - node

cache:
  npm: false

before_script: TARGET_BRANCH=$TRAVIS_BRANCH scripts/check-lib-sync.sh
