os:
- linux
- osx
- windows

dist: focal

language: node_js
node_js:
  - 16
  - 18
  - 20
  - 21

cache:
  npm: false

before_install: if [ "$(node --version | cut -d "." -f 1 | tr -d "v")" -ge 17 ]; then export NODE_OPTIONS="--openssl-legacy-provider"; fi
before_script: TARGET_BRANCH=$TRAVIS_BRANCH scripts/check-lib-sync.sh
